### ISSUE TITLE
[TODO's] Get this working 2023

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/SPMS_ERP_MRPUpdatedRepo#33]
### Description

To get this working in 2023..

Stuff needs to get done:

- [ ] Fix ESLint errors (I use quick-lint-js)
- [ ] Refactor out some of the mess and delete unessesary files and other items
- [ ] Fix Front End
- [ ] Other issues [Placeholder..] cause  too many..

**Comment by gbowne1** [comment]
This also needs to get renamed and rebranded too.
